### ISSUE TITLE
Problem with using the API directly in my Angular app

### ISSUE THREAD

**Issue by kmooi17** [SA-Places-API/support#3] opened 2023-05-07 11:05 UTC
Good day,

I am trying to consume the api directly in my Angular app and I am getting the following error:

`Access to XMLHttpRequest at 'https://api.placesapi.co.za/places/get?searchTerm=cape' from origin 'http://localhost:8100' has been blocked by CORS policy: Request header field apikey is not allowed by Access-Control-Allow-Headers in preflight response.`

Is it possible to add the "apikey" header to the list of allowed headers in the Access-Control-Allow-Headers response header from the server side?

**Comment by Teebo** [comment] 2023-05-07 12:58
Good day,

Thank you. This will be fixed.

**Comment by Teebo** [comment] 2023-05-13 16:05
Good day,

Sorry for the inconvenience.
The issue is resolved.
However, the cors error will still be thrown because you are calling **https** from **http://localhost**.

You can also test your API key at : [https://cors.sh/playground/](https://cors.sh/playground)/ like below

![image](https://github.com/SA-Places-API/support/assets/17063909/9bf5de5c-9027-4f22-b159-c8f4746251a4)

For development, consider using a proxy like [cors-anywhere](https://github.com/Rob--W/cors-anywhere) to consume the API on localhost.

Feel free to reach out if you're still having an issue.

**Comment by kmooi17** [comment] 2023-05-13 16:32
Thanks so much - I appreciate it! @Teebo

**Comment by kmooi17** [comment] 2023-05-13 16:33
Good day,

Thanks so much for the helpful information.

I really appreciate it.


Kind regards
Kane Mooi
+27 74 370 9980

**Closed** 2023-05-13 16:55 UTC
